[package]
name = "linux_bt_proxy"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
prost = "0.13"
prost-types = "0.13"
mdns-sd = "0.13"
mac_address = "1.1"
log = "0.4"
env_logger = "0.11"
bytes = "1"
gethostname = "1.0.2"
libc = "0.2.172"
zbus  = "3"

[build-dependencies]
prost-build = "0.13"
